### PR TITLE
Milestone one

### PR DESCRIPTION
**Pull request by igorkol91**
Created the ERD in the docs folder.
We have 5 tables for a user, post, comment, friend, and likes.
The ERD shows the intended relationships for Adding friends and Press like on a post.

### CODE REVIEW

**Review by elisha2kyakpo1 — CHANGES_REQUESTED** [review]
# Changes Required ♻🛑
Hello there, nice job you've done on this milestone. However, there are still some mandatory changes you should make in order to move on to the next level 🙏😊

<hr>

- [x] One and only one user to have many(or zero) likes.
- [x]  One and only one post to have many(or zero) likes.
Check the image below for reference.
ERD


These are the only changes to make, if you are done, submit another review request.

In case you have a question, find me on slack by searching my name like Elisha kyakopo.

Cheers 💪

Elisha

**Review by taiwo2 — APPROVED** [review]
# STATUS : APPROVED 🎉 
@ZeenatLawal and @igorkol91 Weldone for implementing the suggested changes.
kindly merge and prepare for next task.Thanks

**Comment by ZeenatLawal** [comment]
@taiwo2 You approved this project 2 days ago but it's not reflecting on our dashboards, can you please help us look into it. Thanks:smile:

**Comment by taiwo2** [comment]
Alright I will get back to you and can you please check your dashboard to confirm its reflection

**Comment by ZeenatLawal** [comment]
@taiwo2 It has been fixed. Thank you

**Comment by taiwo2** [comment]
Alright sorry for inconvenience and Thanks for updating me

**Pull request merged**
